### ISSUE TITLE
readDigitalData

### ISSUE THREAD

**Issue by rocksolidsr** [brnluiz/28335ModbusSlave#1]
I have been using this library for a couple of weeks now and it is working pretty well, I have one issue that I can not resolve and was wondering if you could give some help.

For the datahandler_readDigitalData in ModbusDataHandler.c, I'm having trouble reading just one value at a time.  If I read more than one it is fine but if I try to just read one it does not seem to give me the correct value of the input register.  I believe it is somewhere in this portion of the code but can't seem to pin point it.  Any help would be much appreciated.

I was able to get it to work (kinda, for the first 16 variables anyways) with the following code

    // MODIFIABLE: specified address values
    for (idx = 0; idx < numberOfBytes; idx++) {
		    Uint16 coilsNum = totalDataRequested - idx*8;
		    Uint16 padding = idx + firstDataAddress - reg16ReturnIdx;
		    Uint16 content = 0;
		    content = *(dataPtr + padding) >> (reg16ReturnIdx*8);

		if(coilsNum >= 8) {
			slave->dataResponse.content[slave->dataResponse.contentIdx++] = content & 0x00FF;
		} else {
			Uint16 mask;
			mask = ~(0xFFFF << coilsNum);
			if(firstDataAddress<2)
				firstDataAddress = pow(2,firstDataAddress);
			else
				firstDataAddress = pow(2,firstDataAddress)+2;
			//slave->dataResponse.content[slave->dataResponse.contentIdx++] = content & mask;
			slave->dataResponse.content[slave->dataResponse.contentIdx++] = ((*(dataPtr) & (firstDataAddress))!=0);
		}

		if(reg16ReturnIdx == 0) reg16ReturnIdx = 1;
		else reg16ReturnIdx = 0;
	}

**Comment by brnluiz** [comment]
Just to not leave you without feedbacks: I am trying to fix the issue, but I didn't found any yet (and I am working with other embedded projects too). But I didn't forget it yet haha.

**Comment by rocksolidsr** [comment]
its all good, the temporary fix i posted is working for me now

On Fri, Feb 20, 2015 at 11:50 AM, Bruno Luiz Silva <notifications@github.com

**Comment by brnluiz** [comment]
Check the lastest commits. It still have an issue for when you request too much coils: it takes random values after 15~16 itens. Probably I will back to this issue after tweak/organize/modernize the 28335ModbusMaster project.

**Comment by brnluiz** [comment]
I solved it by changing everything for coils/inputs at DataMap and DataHandler.

1. Coils and Inputs are now Uint8 instead of a bit field "1" of Uint16
2. No complex bitwise operations anymore: as it is Uint8, the things works almost the same as for registers
3. The cost of it is that DataMap will cost more memory when created (8 bits x 1 bit)

Check it and test to see if it is ok now

**Comment by rocksolidsr** [comment]
thanks for the update, I'm not sure when I can get around to testing again
but when I do I will let you know.

-Shane
